### ISSUE TITLE
command-line interface

### ISSUE THREAD

**Issue by nabbisen** [nabbisen/htmlproc-rs#2]
```sh
# basic
htmlproc omit_enclosures "<div>...</div>" span
# or (subcommand name: combined with `_` or `-`)
htmlproc omit-enclosures "<div>...</div>" span

# ideal ?
htmlproc omit_enclosures -i some.html -o manipulated.html span p
```

---

```toml
# /htmlproc-rs/Cargo.toml

[workspace]
members = ["bin"]
```

```toml
# /htmlproc-rs/bin/Cargo.toml

[package]
name = "htmlproc-bin"
version = "..."
edition = "2021"

[[bin]]
name = "htmlproc" ?
path = "src/main.rs"

[dependencies]
htmlproc = { path = "../", features = ["full"] }
clap ?
```
